### ISSUE TITLE
webapp deployer api fails with sequence or timeout error

### ISSUE THREAD

**Issue by zramsay** [LaconicNetwork/issues#6]
for example:

```
Error: Query failed with (6): rpc error: code = Unknown desc = account sequence mismatch, expected 78, got 77: incorrect account sequence [cosmos/cosmos-sdk@v0.50.10/x/auth/ante/sigverify.go:290] with gas used: '19196': unknown request
    at QueryClient.queryAbci (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:118:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.request (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/queryclient/utils.js:31:30)
    at async Object.simulate (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/modules/tx/queries.js:44:34)
    at async LaconicClient.simulate (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/signingstargateclient.js:97:29)
    at async LaconicClient.signAndBroadcast (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/signingstargateclient.js:174:35)
```
or

```
    TimeoutError: Transaction with ID 735219F9BCADD08B9F1D968E4E3B6C78C6E9A18C1CDA433CBFFC70508EE3E4CC was submitted but was not yet found on the chain. You might want to check later. There was a wait of 60 seconds.
    at pollForTx (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/stargateclient.js:249:23)
    at pollForTx (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/stargateclient.js:265:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  txId: '735219F9BCADD08B9F1D968E4E3B6C78C6E9A18C1CDA433CBFFC70508EE3E4CC'
}
```

**Comment by prathamesh0** [comment]
@zramsay 
We tried both direct targeted (`vaasl-provider`) and auction based deployment flows from https://deploy.laconic.com
Both seem to be working (see `lrn://laconic-deploy/applications/deploy-test@0.1.24` on https://webapp-deployer-ui.apps.vaasl.io/)
Can you provide more details about the errors please?
What is the scenario in which these errors occurred?
Which process(es) are the error logs from?

**Comment by rxpwnz** [comment]
Hi @prathamesh0 

When webapp-deployer is performing deployment, it may fail due to account sequence issues:

Deployment 1:
```
Error: Query failed with (6): rpc error: code = Unknown desc = account sequence mismatch, expected 78, got 77: incorrect account sequence [cosmos/cosmos-sdk@v0.50.10/x/auth/ante/sigverify.go:290] with gas used: '19196': unknown request
    at QueryClient.queryAbci (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:118:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.request (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/queryclient/utils.js:31:30)
    at async Object.simulate (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/modules/tx/queries.js:44:34)
    at async LaconicClient.simulate (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/signingstargateclient.js:97:29)
    at async LaconicClient.signAndBroadcast (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/signingstargateclient.js:174:35)
```

Deployment 2:
```
TimeoutError: Transaction with ID 735219F9BCADD08B9F1D968E4E3B6C78C6E9A18C1CDA433CBFFC70508EE3E4CC was submitted but was not yet found on the chain. You might want to check later. There was a wait of 60 seconds.
    at pollForTx (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/stargateclient.js:249:23)
    at pollForTx (/usr/lib/node_modules/@cerc-io/laconic-registry-cli/node_modules/@cosmjs/stargate/build/stargateclient.js:265:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  txId: '735219F9BCADD08B9F1D968E4E3B6C78C6E9A18C1CDA433CBFFC70508EE3E4CC'
}
```

It sometimes happens when webapp-deployer is connected to endpoints below:
```
    #rpcEndpoint: 'http://lcn-fin-cluster-control.rxpwnz.xyz:26657'
    #gqlEndpoint: 'http://lcn-fin-cluster-control.rxpwnz.xyz:9473/api
```

Is there a way to mitigate this issue aside from running a non-validator node RPC? Clearing the mempool doesn't seem to help, and the problem often reoccurs after a few broadcasted transactions.

Let me know if you need any additional details.

**Comment by prathamesh0** [comment]
@rxpwnz
- Is the account configured for the deployer (in `webapp-deployer/data/config/laconic.yml`) being used anywhere else?
- Did above mentioned deployments, where the two errors occurred, happen consecutively?

**Comment by rxpwnz** [comment]
@prathamesh0 

 - Account is only used for a validator (which I guess is the issue)
 - Yes, it happened consecutively. After 4 failed attempts I switched RPC to another one and it worked.

**Comment by prathamesh0** [comment]
@rxpwnz 
It's not apparent what the issue is. Looking at txs from the account might help, can you provide the laconic address being used in the deployer please?

**Comment by rxpwnz** [comment]
@prathamesh0 same one that is used for validator: `laconic19h70dln5ktxpc8mcam5nm22glr7h9qtlzvvrtq`

**Comment by prathamesh0** [comment]
@rxpwnz 
Looking at the tx history for given account didn't really help.
We will need access to the machine(s) to debug this further.
